### ISSUE TITLE
Filter alternative

### ISSUE THREAD

**Issue by DigitalPhoneme** [Cpreza24/js-objects-lab#1]
https://github.com/Cpreza24/js-objects-lab/blob/1863551d99d14f36f8ae43a1810c78b243668bea/app.js#L48

Instead of looping through to find a starter, try using ```filter``` to find all starters, then add one to the ```party```

Here's an example:

```// Find and log all starter Pokémon
const starters = pokemon.filter(pkmn => pkmn.starter);
console.log(starters);

// Add the first starter to the party
game.party.push(starters[0]);

```

**Comment by Cpreza24** [comment]
Reading over how I looped through the array vs seeing how filter works I can see how its much more efficient. Thank you!
