### ISSUE TITLE
Removing extra arrays

### ISSUE THREAD

**Issue by DigitalPhoneme** [Cpreza24/js-objects-lab#2]
https://github.com/Cpreza24/js-objects-lab/blob/1863551d99d14f36f8ae43a1810c78b243668bea/app.js#L228

The ```gymStatus``` function could be simplified by removing the extra arrays for ```completedGyms``` and ```incompleteGyms```. Instead, directly count each completed and incomplete gym for a cleaner solution.

```
game.gymStatus = function() {
    const gymTally = { completed: 0, incomplete: 0 };
    
    for (const gym of game.gyms) {
        if (gym.completed) {
            gymTally.completed++;
        } else {
            gymTally.incomplete++;
        }
    }
    
    console.log(gymTally);
};
game.gymStatus();
```

**Comment by Cpreza24** [comment]
This solution is way more readable and does the same thing in much less code. I've adjusted my code to reflect the changes.
