### ISSUE TITLE
Simplifying partyCount method

### ISSUE THREAD

**Issue by DigitalPhoneme** [Cpreza24/js-objects-lab#3]
https://github.com/Cpreza24/js-objects-lab/blob/1863551d99d14f36f8ae43a1810c78b243668bea/app.js#L263

The ```partyCount``` method can be simplified by returning the ``` party.length directly```, as no additional variables are needed

```game.partyCount = function() {
    return game.party.length;
};

console.log(`Number of Pokémon in party: ${game.partyCount()}`);
```

**Comment by Cpreza24** [comment]
I think I really over complicated this one. Fixed the method and simplified the code like you suggested.
